/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    pages: Page;
    blogs: Blog;
    tags: Tag;
    media: Media;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?:
    | (
        | AboutType
        | AdvertiseType
        | HeroType
        | SkillsType
        | ServiceType
        | HeadlineType
        | RecentWorkType
        | TestimonialType
        | TeamType
        | ServiceBannerType
        | ServiceFeaturesType
        | WorkProcessType
        | BannerType
        | OurClientsType
        | StatisticsType
        | TeamInfoType
        | VideoAreaType
        | ListType
        | DetailsType
        | ContactType
        | PageBannerType
        | PricingFeaturesType
        | PricingSectionType
        | FormType
        | DisqusCommentsType
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  isHome?: boolean | null;
  isDynamic?: boolean | null;
  slugMode?: ('generate' | 'custom') | null;
  /**
   * Contains only lowercase letters, numbers, and dashes.
   */
  slug?: string | null;
  pathMode?: ('generate' | 'custom') | null;
  path?: string | null;
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutType".
 */
export interface AboutType {
  /**
   * Enter a short badge title to highlight key information.
   */
  badge_title?: string | null;
  /**
   * Enter the main title for the About section.
   */
  title?: string | null;
  /**
   * Provide a detailed description about this section.
   */
  description?: string | null;
  percentages?:
    | {
        /**
         * Enter a percentage value (0-100).
         */
        percentage?: number | null;
        /**
         * Enter a title corresponding to the percentage value.
         */
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload an image that represents the About section.
   */
  about_image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'About';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    blogImageSize2?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    blogImageSize3?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdvertiseType".
 */
export interface AdvertiseType {
  /**
   * Enter the main title for the advertisement.
   */
  title: string;
  /**
   * Upload an image for the advertisement banner.
   */
  banner_image: number | Media;
  /**
   * Enter the number of completed projects.
   */
  project_completion_count?: string | null;
  /**
   * Enter the current status of the projects.
   */
  completion_status?: string | null;
  /**
   * Provide a detailed description for the advertisement.
   */
  description?: string | null;
  clients?:
    | {
        /**
         * Upload the client’s logo or image.
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * A brief description about the clients featured in the advertisement.
   */
  client_description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Advertise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroType".
 */
export interface HeroType {
  /**
   * Enter the main title for the hero section.
   */
  title: string;
  /**
   * Provide a brief description to accompany the title.
   */
  description?: string | null;
  clients?:
    | {
        /**
         * Upload the client’s logo or image.
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * A brief description about the clients featured in the hero section.
   */
  client_description?: string | null;
  /**
   * Upload the main background image for the hero section.
   */
  hero_image: number | Media;
  /**
   * Enter a badge title if applicable.
   */
  badge_title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillsType".
 */
export interface SkillsType {
  /**
   * Enter the title for the skills section.
   */
  title: string;
  skills?:
    | {
        /**
         * Upload an image representing the skill.
         */
        skill_image: number | Media;
        /**
         * Enter the name of the skill.
         */
        skill_title: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Skills';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceType".
 */
export interface ServiceType {
  /**
   * Enter a short title to highlight the service category.
   */
  badge_title?: string | null;
  /**
   * Main title for the services section.
   */
  title?: string | null;
  services?:
    | {
        /**
         * Select an icon that represents the service.
         */
        service_icon?:
          | (
              | 'flaticon-development'
              | 'flaticon-mobile-development'
              | 'flaticon-brainstorming'
              | 'flaticon-abstract'
              | 'flaticon-ux'
              | 'flaticon-optimization'
              | 'flaticon-goal'
            )
          | null;
        /**
         * Enter the name of the service.
         */
        title?: string | null;
        /**
         * Upload an image that represents the service.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Service';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadlineType".
 */
export interface HeadlineType {
  /**
   * Add multiple headlines to display in this block.
   */
  headlines?:
    | {
        /**
         * The headline text to display.
         */
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Headline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentWorkType".
 */
export interface RecentWorkType {
  /**
   * A short title to highlight the section of recent works.
   */
  badge_title?: string | null;
  /**
   * Main title for the Recent Works section.
   */
  title?: string | null;
  recent_works?:
    | {
        /**
         * Enter the title of the recent work.
         */
        title?: string | null;
        /**
         * Enter Your website url here.
         */
        url?: string | null;
        /**
         * Upload an image representing the recent work.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'RecentWork';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialType".
 */
export interface TestimonialType {
  /**
   * Upload an image to represent the testimonial block.
   */
  image?: (number | null) | Media;
  /**
   * Add individual testimonials from reviewers.
   */
  testimonials?:
    | {
        /**
         * Enter the name of the reviewer.
         */
        reviewer_name?: string | null;
        /**
         * Write the testimonial review here.
         */
        review?: string | null;
        /**
         * Upload an image of the reviewer.
         */
        reviewer_image?: (number | null) | Media;
        /**
         * Specify the role or position of the reviewer.
         */
        reviewer_role?: string | null;
        /**
         * Rate the testimonial between 1 and 5.
         */
        rating?: number | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamType".
 */
export interface TeamType {
  /**
   * Title displayed on the team block badge.
   */
  badge_title?: string | null;
  /**
   * Main title for the team section.
   */
  title?: string | null;
  /**
   * Add team members to display in this block.
   */
  team_members?:
    | {
        /**
         * Upload the team member’s photo.
         */
        image?: (number | null) | Media;
        /**
         * Enter the team member’s name.
         */
        name?: string | null;
        /**
         * Specify the team member’s role or position.
         */
        role?: string | null;
        /**
         * Add social media links for the team member.
         */
        social_media?:
          | {
              icon?:
                | (
                    | 'fab fa-facebook-f'
                    | 'fab fa-instagram'
                    | 'fab fa-whatsapp'
                    | 'fab fa-twitter'
                    | 'fab fa-linkedin-in'
                  )
                | null;
              /**
               * Enter the URL of the social media profile.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceBannerType".
 */
export interface ServiceBannerType {
  /**
   * Enter the title for the service banner.
   */
  title: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ServiceBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceFeaturesType".
 */
export interface ServiceFeaturesType {
  features?:
    | {
        /**
         * Enter the feature title.
         */
        title?: string | null;
        /**
         * Enter url.
         */
        url?: string | null;
        /**
         * Provide a detailed description of the feature.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ServiceFeatures';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkProcessType".
 */
export interface WorkProcessType {
  steps?:
    | {
        /**
         * Enter the title of the step.
         */
        title?: string | null;
        /**
         * Provide a detailed description of this step.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'WorkProcess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerType".
 */
export interface BannerType {
  /**
   * Enter the main title for the banner section.
   */
  title?: string | null;
  /**
   * Upload the first banner image. Recommended dimensions: [insert dimensions].
   */
  banner_image1?: (number | null) | Media;
  /**
   * Upload the second banner image. Recommended dimensions: [insert dimensions].
   */
  banner_image2?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurClientsType".
 */
export interface OurClientsType {
  /**
   * Enter a title for the clients section.
   */
  title?: string | null;
  /**
   * Add logos of the clients. You can upload multiple logos.
   */
  clients?:
    | {
        /**
         * Upload the logo of the client.
         */
        client_logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'OurClients';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatisticsType".
 */
export interface StatisticsType {
  /**
   * Add individual statistics with a number and title.
   */
  statistics?:
    | {
        /**
         * Enter the numerical value for the statistic.
         */
        number?: number | null;
        /**
         * Provide a title for the statistic.
         */
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Statistics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamInfoType".
 */
export interface TeamInfoType {
  /**
   * A short caption that introduces the team section.
   */
  caption?: string | null;
  /**
   * The main title for the team section.
   */
  title?: string | null;
  features?:
    | {
        /**
         * The title of the feature.
         */
        title?: string | null;
        /**
         * A detailed description of the feature.
         */
        description?: string | null;
        /**
         * Select an icon that represents the feature.
         */
        icon?: ('flaticon-creativity' | 'flaticon-mobile-banking' | 'flaticon-optimization-1') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TeamInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoAreaType".
 */
export interface VideoAreaType {
  /**
   * Upload an image to represent the video. Recommended dimensions: [insert dimensions].
   */
  video_image?: (number | null) | Media;
  /**
   * Enter the URL for the video. Supported platforms: YouTube, Vimeo, etc.
   */
  video_link?: string | null;
  /**
   * Provide a brief description of the video content.
   */
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'VideoArea';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListType".
 */
export interface ListType {
  title?: string | null;
  description?: string | null;
  collectionSlug?: ('blogs' | 'tags' | 'users') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'List';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DetailsType".
 */
export interface DetailsType {
  collectionSlug?: ('blogs' | 'tags' | 'users') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Details';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactType".
 */
export interface ContactType {
  /**
   * Enter a brief subtitle for the contact section.
   */
  sub_title?: string | null;
  /**
   * Enter the main title for the contact section.
   */
  title?: string | null;
  /**
   * Enter any background text to display behind the contact form or section.
   */
  background_text?: string | null;
  /**
   * Enter the text for the button in the contact section.
   */
  button_text?: string | null;
  /**
   * Enter the URL that the button should link to.
   */
  button_url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBannerType".
 */
export interface PageBannerType {
  /**
   * Enter the name of the page to display on the banner.
   */
  page_name: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'PageBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingFeaturesType".
 */
export interface PricingFeaturesType {
  /**
   * Enter a subtitle for the pricing features section.
   */
  sub_title?: string | null;
  /**
   * Enter the main title for the pricing features section.
   */
  title?: string | null;
  /**
   * Add details related to the pricing features.
   */
  datails?:
    | {
        /**
         * Enter the heading for this detail.
         */
        heading?: string | null;
        /**
         * Provide a description for this detail.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enter the text for the button in the pricing features section.
   */
  button_text?: string | null;
  /**
   * Enter the URL or path for the button to link to.
   */
  button_path?: string | null;
  /**
   * List the features associated with the pricing plans.
   */
  features?:
    | {
        /**
         * Select an icon to represent the feature.
         */
        icons?: ('fa-bezier-curve' | 'fa-cogs' | 'fa-chart-pie' | 'fa-shield-cross') | null;
        /**
         * Enter the title of the feature.
         */
        title?: string | null;
        /**
         * Provide a description of the feature.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'PricingFeatures';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingSectionType".
 */
export interface PricingSectionType {
  /**
   * Enter the main title for the pricing section.
   */
  title?: string | null;
  /**
   * Enter a subtitle for the pricing section.
   */
  sub_title?: string | null;
  /**
   * Add pricing packages with details.
   */
  pricing?:
    | {
        /**
         * Select an icon to represent this pricing package.
         */
        icons?: ('flaticon-abstract' | 'flaticon-liquid' | 'flaticon-petals') | null;
        /**
         * Enter the title for this pricing package.
         */
        package_title?: string | null;
        /**
         * Enter the price for this package.
         */
        price?: number | null;
        /**
         * Add any additional text related to the price, e.g., "per month".
         */
        price_text?: string | null;
        /**
         * List the features available in this pricing package.
         */
        available_features?:
          | {
              /**
               * Enter a feature of this pricing package.
               */
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Enter the text for the button associated with this package.
         */
        button_text?: string | null;
        /**
         * Enter the URL for the button action.
         */
        button_url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'PricingSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormType".
 */
export interface FormType {
  title: string;
  form: {
    relationTo: 'forms';
    value: number | Form;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'FormBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?:
              | {
                  [k: string]: unknown;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DisqusCommentsType".
 */
export interface DisqusCommentsType {
  title?: string | null;
  /**
   * To find your Disqus shortname, log into Disqus, access the Admin panel, and check the URL or General Site Settings.
   */
  shortName: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'DisqusComments';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  /**
   * Upload blog image
   */
  blogImage: number | Media;
  title: string;
  /**
   * Add the summary of the blog post
   */
  description: string;
  tags?:
    | {
        relationTo: 'tags';
        value: number | Tag;
      }[]
    | null;
  author?:
    | {
        relationTo: 'users';
        value: number | User;
      }[]
    | null;
  /**
   * Main content of the blog post. Use the rich text editor for formatting.
   */
  content: {
    [k: string]: unknown;
  }[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Contains only lowercase letters, numbers, and dashes.
   */
  slug?: string | null;
  /**
   * Save it as draft to schedule.
   */
  publishOn?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Upload tag image
   */
  tagImage: number | Media;
  title: string;
  description: string;
  color?: ('blue' | 'gray' | 'red' | 'green' | 'yellow' | 'indigo' | 'purple' | 'pink') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Contains only lowercase letters, numbers, and dashes.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  /**
   * Contains only lowercase letters, numbers, and dashes.
   */
  username: string;
  imageUrl?: (number | null) | Media;
  role: ('admin' | 'author' | 'user')[];
  emailVerified?: string | null;
  socialLinks?:
    | {
        platform:
          | 'website'
          | 'facebook'
          | 'instagram'
          | 'twitter'
          | 'linkedin'
          | 'youtube'
          | 'tiktok'
          | 'pinterest'
          | 'snapchat'
          | 'reddit'
          | 'tumblr'
          | 'whatsapp'
          | 'telegram'
          | 'github'
          | 'medium'
          | 'quora'
          | 'discord';
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'blogs';
        value: number | Blog;
      }
    | {
        relationTo: 'tags';
        value: number | Tag;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        About?: T | AboutTypeSelect<T>;
        Advertise?: T | AdvertiseTypeSelect<T>;
        Hero?: T | HeroTypeSelect<T>;
        Skills?: T | SkillsTypeSelect<T>;
        Service?: T | ServiceTypeSelect<T>;
        Headline?: T | HeadlineTypeSelect<T>;
        RecentWork?: T | RecentWorkTypeSelect<T>;
        Testimonial?: T | TestimonialTypeSelect<T>;
        Team?: T | TeamTypeSelect<T>;
        ServiceBanner?: T | ServiceBannerTypeSelect<T>;
        ServiceFeatures?: T | ServiceFeaturesTypeSelect<T>;
        WorkProcess?: T | WorkProcessTypeSelect<T>;
        Banner?: T | BannerTypeSelect<T>;
        OurClients?: T | OurClientsTypeSelect<T>;
        Statistics?: T | StatisticsTypeSelect<T>;
        TeamInfo?: T | TeamInfoTypeSelect<T>;
        VideoArea?: T | VideoAreaTypeSelect<T>;
        List?: T | ListTypeSelect<T>;
        Details?: T | DetailsTypeSelect<T>;
        Contact?: T | ContactTypeSelect<T>;
        PageBanner?: T | PageBannerTypeSelect<T>;
        PricingFeatures?: T | PricingFeaturesTypeSelect<T>;
        PricingSection?: T | PricingSectionTypeSelect<T>;
        FormBlock?: T | FormTypeSelect<T>;
        DisqusComments?: T | DisqusCommentsTypeSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  isHome?: T;
  isDynamic?: T;
  slugMode?: T;
  slug?: T;
  pathMode?: T;
  path?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutType_select".
 */
export interface AboutTypeSelect<T extends boolean = true> {
  badge_title?: T;
  title?: T;
  description?: T;
  percentages?:
    | T
    | {
        percentage?: T;
        title?: T;
        id?: T;
      };
  about_image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdvertiseType_select".
 */
export interface AdvertiseTypeSelect<T extends boolean = true> {
  title?: T;
  banner_image?: T;
  project_completion_count?: T;
  completion_status?: T;
  description?: T;
  clients?:
    | T
    | {
        image?: T;
        id?: T;
      };
  client_description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroType_select".
 */
export interface HeroTypeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  clients?:
    | T
    | {
        image?: T;
        id?: T;
      };
  client_description?: T;
  hero_image?: T;
  badge_title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillsType_select".
 */
export interface SkillsTypeSelect<T extends boolean = true> {
  title?: T;
  skills?:
    | T
    | {
        skill_image?: T;
        skill_title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceType_select".
 */
export interface ServiceTypeSelect<T extends boolean = true> {
  badge_title?: T;
  title?: T;
  services?:
    | T
    | {
        service_icon?: T;
        title?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadlineType_select".
 */
export interface HeadlineTypeSelect<T extends boolean = true> {
  headlines?:
    | T
    | {
        title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentWorkType_select".
 */
export interface RecentWorkTypeSelect<T extends boolean = true> {
  badge_title?: T;
  title?: T;
  recent_works?:
    | T
    | {
        title?: T;
        url?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialType_select".
 */
export interface TestimonialTypeSelect<T extends boolean = true> {
  image?: T;
  testimonials?:
    | T
    | {
        reviewer_name?: T;
        review?: T;
        reviewer_image?: T;
        reviewer_role?: T;
        rating?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamType_select".
 */
export interface TeamTypeSelect<T extends boolean = true> {
  badge_title?: T;
  title?: T;
  team_members?:
    | T
    | {
        image?: T;
        name?: T;
        role?: T;
        social_media?:
          | T
          | {
              icon?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceBannerType_select".
 */
export interface ServiceBannerTypeSelect<T extends boolean = true> {
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceFeaturesType_select".
 */
export interface ServiceFeaturesTypeSelect<T extends boolean = true> {
  features?:
    | T
    | {
        title?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkProcessType_select".
 */
export interface WorkProcessTypeSelect<T extends boolean = true> {
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerType_select".
 */
export interface BannerTypeSelect<T extends boolean = true> {
  title?: T;
  banner_image1?: T;
  banner_image2?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurClientsType_select".
 */
export interface OurClientsTypeSelect<T extends boolean = true> {
  title?: T;
  clients?:
    | T
    | {
        client_logo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatisticsType_select".
 */
export interface StatisticsTypeSelect<T extends boolean = true> {
  statistics?:
    | T
    | {
        number?: T;
        title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamInfoType_select".
 */
export interface TeamInfoTypeSelect<T extends boolean = true> {
  caption?: T;
  title?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoAreaType_select".
 */
export interface VideoAreaTypeSelect<T extends boolean = true> {
  video_image?: T;
  video_link?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListType_select".
 */
export interface ListTypeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  collectionSlug?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DetailsType_select".
 */
export interface DetailsTypeSelect<T extends boolean = true> {
  collectionSlug?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactType_select".
 */
export interface ContactTypeSelect<T extends boolean = true> {
  sub_title?: T;
  title?: T;
  background_text?: T;
  button_text?: T;
  button_url?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBannerType_select".
 */
export interface PageBannerTypeSelect<T extends boolean = true> {
  page_name?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingFeaturesType_select".
 */
export interface PricingFeaturesTypeSelect<T extends boolean = true> {
  sub_title?: T;
  title?: T;
  datails?:
    | T
    | {
        heading?: T;
        description?: T;
        id?: T;
      };
  button_text?: T;
  button_path?: T;
  features?:
    | T
    | {
        icons?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingSectionType_select".
 */
export interface PricingSectionTypeSelect<T extends boolean = true> {
  title?: T;
  sub_title?: T;
  pricing?:
    | T
    | {
        icons?: T;
        package_title?: T;
        price?: T;
        price_text?: T;
        available_features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        button_text?: T;
        button_url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormType_select".
 */
export interface FormTypeSelect<T extends boolean = true> {
  title?: T;
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DisqusCommentsType_select".
 */
export interface DisqusCommentsTypeSelect<T extends boolean = true> {
  title?: T;
  shortName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  blogImage?: T;
  title?: T;
  description?: T;
  tags?: T;
  author?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishOn?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tagImage?: T;
  title?: T;
  description?: T;
  color?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        blogImageSize2?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        blogImageSize3?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  username?: T;
  imageUrl?: T;
  role?: T;
  emailVerified?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  general: {
    title: string;
    description: string;
    /**
     * We recommend a maximum size of 256 * 256 pixels
     */
    faviconUrl: number | Media;
    /**
     * We recommend a maximum size of 1200 * 630 pixels
     */
    ogImageUrl: number | Media;
    keywords?: string[] | null;
  };
  navbar: {
    logo: BrandLogo;
    menuLinks?:
      | {
          /**
           * Check to create group of links
           */
          group?: boolean | null;
          menuLink?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            /**
             * Upload an svg or logo to be displayed with link
             */
            icon?: (number | null) | Media;
            label: string;
            page?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            id?: string | null;
          };
          menuLinkGroup?: {
            groupTitle: string;
            groupLinks?:
              | {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  /**
                   * Upload an svg or logo to be displayed with link
                   */
                  icon?: (number | null) | Media;
                  label: string;
                  page?: {
                    relationTo: 'pages';
                    value: number | Page;
                  } | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  footer: {
    logo: BrandLogo;
    footerLinks?:
      | {
          /**
           * Check to create group of links
           */
          group?: boolean | null;
          menuLink?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            /**
             * Upload an svg or logo to be displayed with link
             */
            icon?: (number | null) | Media;
            label: string;
            page?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            id?: string | null;
          };
          menuLinkGroup?: {
            groupTitle: string;
            groupLinks?:
              | {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  /**
                   * Upload an svg or logo to be displayed with link
                   */
                  icon?: (number | null) | Media;
                  label: string;
                  page?: {
                    relationTo: 'pages';
                    value: number | Page;
                  } | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
    socialLinks?:
      | {
          platform:
            | 'website'
            | 'facebook'
            | 'instagram'
            | 'twitter'
            | 'linkedin'
            | 'youtube'
            | 'tiktok'
            | 'pinterest'
            | 'snapchat'
            | 'reddit'
            | 'tumblr'
            | 'whatsapp'
            | 'telegram'
            | 'github'
            | 'medium'
            | 'quora'
            | 'discord';
          value: string;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
  };
  redirectionLinks?: {
    /**
     * This redirects to a blog details page
     */
    blogLink?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    /**
     * This redirect to a product details page
     */
    productLink?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    /**
     * This redirects to a author details page
     */
    authorLink?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    /**
     * This redirects to a tag details page
     */
    tagLink?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
  };
  monetization?: {
    /**
     * Add the publisher-id from Google AdSense Console
     */
    adSenseId?: string | null;
    /**
     * Add the measurement id from Google Analytics dashboard
     */
    measurementId?: string | null;
  };
  stripeConnect?: {
    country?:
      | (
          | 'AL'
          | 'DZ'
          | 'AO'
          | 'AG'
          | 'AR'
          | 'AM'
          | 'AU'
          | 'AT'
          | 'AZ'
          | 'BS'
          | 'BH'
          | 'BD'
          | 'BE'
          | 'BJ'
          | 'BT'
          | 'BO'
          | 'BA'
          | 'BW'
          | 'BN'
          | 'BG'
          | 'KH'
          | 'CA'
          | 'CL'
          | 'CO'
          | 'CR'
          | 'CI'
          | 'HR'
          | 'CY'
          | 'CZ'
          | 'DK'
          | 'DO'
          | 'EC'
          | 'EG'
          | 'SV'
          | 'EE'
          | 'ET'
          | 'FI'
          | 'FR'
          | 'GA'
          | 'GM'
          | 'DE'
          | 'GH'
          | 'GR'
          | 'GT'
          | 'GY'
          | 'HK'
          | 'HU'
          | 'IS'
          | 'IN'
          | 'ID'
          | 'IE'
          | 'IL'
          | 'IT'
          | 'JM'
          | 'JP'
          | 'JO'
          | 'KZ'
          | 'KE'
          | 'KW'
          | 'LA'
          | 'LV'
          | 'LI'
          | 'LT'
          | 'LU'
          | 'MO'
          | 'MG'
          | 'MY'
          | 'MT'
          | 'MU'
          | 'MX'
          | 'MD'
          | 'MC'
          | 'MN'
          | 'MA'
          | 'MZ'
          | 'NA'
          | 'NL'
          | 'NZ'
          | 'NE'
          | 'NG'
          | 'MK'
          | 'NO'
          | 'OM'
          | 'PK'
          | 'PA'
          | 'PY'
          | 'PE'
          | 'PH'
          | 'PL'
          | 'PT'
          | 'QA'
          | 'RO'
          | 'RW'
          | 'SM'
          | 'SA'
          | 'SN'
          | 'RS'
          | 'SG'
          | 'SK'
          | 'SI'
          | 'ZA'
          | 'KR'
          | 'ES'
          | 'LK'
          | 'LC'
          | 'SE'
          | 'CH'
          | 'TW'
          | 'TZ'
          | 'TH'
          | 'TT'
          | 'TN'
          | 'TR'
          | 'AE'
          | 'GB'
          | 'UY'
          | 'UZ'
          | 'VN'
        )
      | null;
    currency?:
      | (
          | 'usd'
          | 'eur'
          | 'inr'
          | 'gbp'
          | 'jpy'
          | 'cad'
          | 'aud'
          | 'chf'
          | 'cny'
          | 'hkd'
          | 'sgd'
          | 'mxn'
          | 'brl'
          | 'rub'
          | 'krw'
          | 'zar'
          | 'try'
          | 'sar'
          | 'aed'
          | 'pln'
        )
      | null;
    /**
     * Auto generated by stripe after successful stripe connect
     */
    stripeUserId?: string | null;
    /**
     * Auto generated by stripe after successful stripe connect
     */
    stripeAdminDashboard?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandLogo".
 */
export interface BrandLogo {
  imageUrl: number | Media;
  /**
   * Adjust to the height of the logo
   */
  height?: number | null;
  /**
   * Adjust to the width of the logo
   */
  width?: number | null;
  /**
   * This text appears below the footer image
   */
  description?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        title?: T;
        description?: T;
        faviconUrl?: T;
        ogImageUrl?: T;
        keywords?: T;
      };
  navbar?:
    | T
    | {
        logo?: T | BrandLogoSelect<T>;
        menuLinks?:
          | T
          | {
              group?: T;
              menuLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    id?: T;
                  };
              menuLinkGroup?:
                | T
                | {
                    groupTitle?: T;
                    groupLinks?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  footer?:
    | T
    | {
        logo?: T | BrandLogoSelect<T>;
        footerLinks?:
          | T
          | {
              group?: T;
              menuLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    id?: T;
                  };
              menuLinkGroup?:
                | T
                | {
                    groupTitle?: T;
                    groupLinks?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              value?: T;
              id?: T;
            };
        copyright?: T;
      };
  redirectionLinks?:
    | T
    | {
        blogLink?: T;
        productLink?: T;
        authorLink?: T;
        tagLink?: T;
      };
  monetization?:
    | T
    | {
        adSenseId?: T;
        measurementId?: T;
      };
  stripeConnect?:
    | T
    | {
        country?: T;
        currency?: T;
        stripeUserId?: T;
        stripeAdminDashboard?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandLogo_select".
 */
export interface BrandLogoSelect<T extends boolean = true> {
  imageUrl?: T;
  height?: T;
  width?: T;
  description?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}